# Generated by Django 5.1.2 on 2025-04-12 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('distance_from_center', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('star_rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')])),
                ('image_url', models.URLField(blank=True)),
                ('free_cancellation', models.BooleanField(default=True)),
                ('no_prepayment', models.BooleanField(default=True)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('breakfast_included', models.BooleanField(default=False)),
                ('has_restaurant', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('room_service', models.BooleanField(default=False)),
                ('has_sea_view', models.BooleanField(default=False)),
                ('has_24_hour_front_desk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='place_pic/')),
                ('km', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('outdoor', 'Outdoor'), ('relax', 'Relax'), ('romance', 'Romance')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
