# Generated by Django 5.2 on 2025-04-25 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_remove_travelplan_created_by_travelreview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelreview',
            options={'ordering': ['-created_at'], 'permissions': [('can_moderate', 'Can approve or delete reviews')]},
        ),
        migrations.AddField(
            model_name='travelreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='travelreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★ Poor'), (2, '★★ Fair'), (3, '★★★ Good'), (4, '★★★★ Very Good'), (5, '★★★★★ Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
